apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-producer
spec:
  selector:
    matchLabels:
      app: task-producer
  template:
    metadata:
      labels:
        app: task-producer
    spec:
      containers:
      - name: task-producer
        image: rgan19/task-producer:1.0.0
        resources:
          limits: 
            memory: "1024Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
        env:
        - name: RABBITMQ_HOST
          value: "rabbitmq"
        - name: RABBITMQ_PORT
          value: "5672"

     
---
apiVersion: v1
kind: Service
metadata:
  name: task-producer
spec:
  type: NodePort
  selector:
    app: task-producer
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 31500